user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  # Logs
  log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" cid=$http_x_correlation_id';
  access_log /var/log/nginx/access.log main;
  error_log  /var/log/nginx/error.log warn;

  sendfile on;
  keepalive_timeout 65;
  client_max_body_size 20m;

  # Rate limit por IP - protege /auth/login (Security Monkey)
  limit_req_zone $binary_remote_addr zone=auth_zone:10m rate=10r/m;

  include /etc/nginx/conf.d/*.conf;
}
